apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storagerolebindings.csmauth.storage.dell.com
spec:
  group: csmauth.storage.dell.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                tenant:
                  type: string
                role:
                  type: string
  scope: Cluster
  names:
    plural: storagerolebindings
    singular: storagerolebinding
    kind: DellStorageRoleBinding
    shortNames:
    - strb