apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storagetenants.csmauth.storage.dell.com
spec:
  group: csmauth.storage.dell.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                volume-prefix:
                  type: string
  scope: Cluster
  names:
    plural: storagetenants
    singular: storagetenant
    kind: StorageTenant
    shortNames:
    - st