apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dellstorages.csmauth.storage.dell.com
spec:
  group: csmauth.storage.dell.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                endpoint:
                  type: string
                systemid:
                  type: string
  scope: Cluster
  names:
    plural: dellstorages
    singular: dellstorage
    kind: DellStorage
    shortNames:
    - dellst