apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageroles.csmauth.storage.dell.com
spec:
  group: csmauth.storage.dell.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                storage:
                  # "name of storage.csamauth.storage.dell.com"
                  type: string
                quota:
                  # "pool1=100GB"
                  type: string
  scope: Cluster
  names:
    plural: storageroles
    singular: storagerole
    kind: StorageRole
    shortNames:
    - str