kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: postgres-data
spec:
  storageClassName: vxflexos
  accessModes:
     - ReadWriteOnce
  resources:
     requests:
       storage: 16Gi
---


apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  EXAMPLE_DB_HOST: postgres://postgres@postgres/example?sslmode=disable
  EXAMPLE_DB_KIND: postgres
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin123

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    podmon.dellemc.com/driver: csi-vxflexos
spec:
  selector:
    matchLabels:
      app: postgres
      podmon.dellemc.com/driver: csi-vxflexos
  template:
    metadata:
      labels:
        app: postgres
        podmon.dellemc.com/driver: csi-vxflexos
    spec:
      containers:
      - image: "postgres:10.1"
        name: postgres
        envFrom:
        - configMapRef:
            name: example-config
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data
---

apiVersion: v1
kind: Service
metadata:
  name: pg-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432